`transpose()`的本质是交换axis

In [1]:
import numpy as np

In [2]:
arr0=np.arange(2*3*4).reshape(2,3,4)
arr0

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
# 默认的transpose()顺序是逆序, 也就是((2, 1, 0))
arr1=arr0.transpose()
arr1.shape

(4, 3, 2)

In [4]:
arr1

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [5]:
arr2=arr0.transpose((0, 2, 1))
arr2.shape

(2, 4, 3)

In [6]:
arr2

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])